# Copyright (c) 2018, Reed O'Brien
# All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

image: reed/leche:latest
# services:
#   - postgres

stages:
  - build
  - test

# - deploy

metalint:
    image: reed/leche:latest
    stage: build
    script:
        - mkdir -p /go/src/gitlab.com/reedobrien
        - ln -s /builds/reedobrien/s3cp /go/src/gitlab.com/reedobrien/s3cp
        - go get github.com/alecthomas/gometalinter
        - make develop
        - make lint
        - gometalinter --install
        - (unformatted=$(goimports -l -e .); if [ -n "$unformatted" ]; then echo >&2 Go files must be formatted with goimports.; for filename in $unformatted; do echo >&2 "failed goimports    $PWD/$filename"; done; exit 1; fi )
        - go vet gitlab.com/reedobrien/s3cp
        - go tool vet -shadowstrict .
        - gometalinter ./...

compile-go:
  image: reed/leche:latest
  stage: build
  script:
      - mkdir -p /go/src/gitlab.com/reedobrien
      - ln -s /builds/reedobrien/s3cp /go/src/gitlab.com/reedobrien/s3cp
      - make build  
      - go build ./...
    # Loop through src/*.go, go build, if exit code is not 0, then exit 66
    # - (for f in src/*.go; do echo "-> go build $f"; go build $f; if [ $? -ne 0 ]; then exit 66; fi; done);

test-go:
  image: reed/leche:latest
  # services:
    # - postgres:9.4
    # - truongsinh/rethinkdb:2.1.3
  stage: test
  script:
    # - go run sql/latest_schema.sql.go
    - mkdir -p /go/src/gitlab.com/reedobrien
    - ln -s /builds/reedobrien/s3cp /go/src/gitlab.com/reedobrien/s3cp
    - make develop 
    - make test
    - go test -race ./...
    - go test -coverprofile=coverage.txt -covermode=atomic gitlab.com/reedobrien/s3cp
    - bash <(curl -s https://codecov.io/bash)


